### ISSUE TITLE
Made a fix for the missing value for DPS index. Please add it to the next release!!!

### ISSUE THREAD

**Issue by nikrays** [rospogrigio/localtuya#1003]
Expand code in common.py file to

```
#    def dps(self, dp_index):
        """Return cached value for DPS index."""

        value = self._status.get(str(dp_index))
        # self.warning(self._status)
    
        if dp_index == 24 and value is None:
            return '00EA02B203E8'

        if value is None:
            self.warning(
                "Entity %s is requesting unknown DPS index %s",
                self.entity_id,
                dp_index,
            )

        return value
```

**Comment by nikrays** [comment]
Dear @rospogrigio Dear dick, take a look at my pull request https://github.com/rospogrigio/localtuya/pull/1321, please add if not difficult to the next build, it will help a lot of people. There is evidence of viability. I remind you that this solves the problem:

________________________________________________________

This error occurred in custom integration.

Logger: custom_components.localtuya.light
Source: custom_components/localtuya/pytuya/__init__.py:255
Integration: LocalTuya integration (documentation, issues)
First occurred: 19:23:45 (8 occurrences)
Last logged: 19:24:34

[bfb...u29] Entity light.hallway_lightning is requesting unknown DPS index 24

_______________________________________________________________

And:

_______________________________________________________________

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/localtuya/light.py:285
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 19:24:33 (4 occurrences)
Last logged: 19:24:34

[547666186720] object of type 'NoneType' has no len()
Traceback (most recent call last):
   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 198, in handle_call_service
     await hass.services.async_call(
   File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
     task.result()
   File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
     await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
     await service.entity_service_call(
   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
     future.result() # pop exception if have
   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
     await coro
   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
     await result
   File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 572, in async_handle_light_on_service
     await light.async_turn_on(**filter_turn_on_params(light, params))
   File "/config/custom_components/localtuya/light.py", line 358, in async_turn_on
     if self.__is_color_rgb_encoded():
   File "/config/custom_components/localtuya/light.py", line 285, in __is_color_rgb_encoded
     return len(self.dps_conf(CONF_COLOR)) > 12
TypeError: object of type 'NoneType' has no len()

_______________________________________________________________

**Comment by Mattis-Seehaus** [comment]
I don´t know if this error persists for many people, but in 1/5 of my lights, it still is the case..

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/localtuya/light.py:285
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 13:18:11 (1 occurrences)
Last logged: 13:18:11

[139796329890960] object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 582, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/localtuya/light.py", line 358, in async_turn_on
    if self.__is_color_rgb_encoded():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/light.py", line 285, in __is_color_rgb_encoded
    return len(self.dps_conf(CONF_COLOR)) > 12
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

**Comment by nikrays** [comment]
Logger: custom_components.localtuya.light
Source: custom_components/localtuya/pytuya/__init__.py:255
Integration: LocalTuya integration (documentation, issues)
First occurred: 14 июля 2023 г. в 17:52:23 (25 occurrences)
Last logged: 15 июля 2023 г. в 22:51:33

[bfb...u29] Entity light.hallway_lightning is requesting unknown DPS index 24

**Comment by Brightyfalls** [comment]
Hi! Thank you very much for the fix! Fixed the issue "TypeError: object of type 'NoneType' has no len()" completely for me.

**Comment by nikrays** [comment]
It’s just that the developer doesn’t care, he’s too lazy to add a few lines, despite the fact that many people report that my method works..

**Comment by rospogrigio** [comment]
Ehi, just to be clear: it's not laziness, it's just that I don't like this implementation. One question: have you tried to input the DP 24 in one of the "Manual DPS to add" or "DPISs to send in RESET command" fields? 

![image](https://github.com/rospogrigio/localtuya/assets/49229287/3f8ad8a9-d92b-481d-b653-4db099059e0f)

Maybe it could fix your problem. If it does not, I would prefer to make this more general, such as introduce a field to define a {dp: custom default value} field for a group of desired DPs, to be used in cases like these. But it takes time and I'm too involved in other stuff currently, such as Zigbee support so if anybody wants to contribute, it would be very welcome.

**Comment by Brightyfalls** [comment]
> One question: have you tried to input the DP 24 in one of the "Manual DPS to add" or "DPISs to send in RESET command" fields?
Nope, I haven't tried that since DP detection worked normally. Besides, I am not entirely sure how to leverage these fields because I get a lot of errors regarding other DPs as well. It is manifested by my lights sometimes randomly losing connection with local tuya. Then I have to use Smart Life app to turn them, for example, off and on again. After that, the lights become controllable again. However, I think I should open a separate issue for that at some point.

**Comment by rospogrigio** [comment]
Well that seems to be an issue that could definitely be solved with the Manual DPS... field, just input the missing DP there and try...

**Comment by Brightyfalls** [comment]
> Well that seems to be an issue that could definitely be solved with the Manual DPS... field, just input the missing DP there and try...

Manually input all the DPs I get errors about, right?

**Comment by rospogrigio** [comment]
Yes, separated by commas, I believe.

**Comment by chriswood1001** [comment]
I have multiple Tuya lights that all used to change colour, but now some of them have begun to return this "Object of type NoneType has no len()" error. They originally had DPS 24 when first set up, but removing the bulb and re-adding it reveals DPS 24 is now absent. Adding 24 to the "Manual DPS to add" section allows me to select it on the next screen, but the error still persists when I try to select a light colour. I'm stuck, and also don't understand why the DPS disappeared for certain lights.

**Comment by nikrays** [comment]
> I have multiple Tuya lights that all used to change colour, but now some of them have begun to return this "Object of type NoneType has no len()" error. They originally had DPS 24 when first set up, but removing the bulb and re-adding it reveals DPS 24 is now absent. Adding 24 to the "Manual DPS to add" section allows me to select it on the next screen, but the error still persists when I try to select a light colour. I'm stuck, and also don't understand why the DPS disappeared for certain lights.

Forget it, the developer doesn’t care, he won’t do anything and the integration is generally abandoned, as an option I can suggest my method from the issue header, I’m 1000% sure that everything will work

**Comment by chriswood1001** [comment]
I appreciate all the work rospogrigio has put into making this local integration possible in the first place. That shouldn't be overlooked.

I did find a non-coding solution that worked on every light that mysteriously dropped DPI 24. I opened my Tuya app, connected to the bulb, set it to a color and then went back to HA. That somehow "reminded?" the bulb that it should have color capabilities and HA immediately showed the color state and allowed me to begin changing it again. Worked 14 times in a row for every bulb that mysteriously began giving me this problem.

**Comment by nikrays** [comment]
> Just to make it clear: it's not that I don't care but it's a hell of a period for me (also personally). Regarding this specific issue, I repeat what I have always said: I understand the intention behind this fix but this is not the way the SW should be coded, it should be made more general because this "disappearing DP" issue also happens on other devices, in other DPs. For example, I have a remote switch that suddenly drops the DP 1 (the STATUS of the switch!!!), and the solution also on my device is to toggle it with the Tuysa app to make it appear again... but unfortunately it's not possible to do it as desired since it is the switch that controls all the main power plugs of the house (so fridge, washing machine, etc...). So, in my case the "ghost" DP would be different from 24, and the default value would need to be different from the hardcoded value that your device needs. We need to design and code it properly. This said, I'll be happy to do it when I can but I'm too busy on too many things right now, in the meantime you can add the patch that @nikrays suggested which will fix your issue probably. Thank you all for your understanding, bye

Of course, we are waiting for the return, there were also warnings after the last update HA 2024, and I’m wondering whether it’s worth fixing them yourself or will you release a patch soon?

**Comment by racinmat** [comment]
Hi, I tried to add the manual DPS 24
![image](https://github.com/user-attachments/assets/d7be3781-5c2a-464d-9c79-599d6390cdfd)
but even after filling it there I still don't see it in the color field:
![image](https://github.com/user-attachments/assets/b0e22cc8-f0c7-4d6e-99ef-e08874f010cc)

what am I doing wrong?

**Comment by jehy** [comment]
Manual DPS did not help me, but hack from the first post did.
