### ISSUE TITLE
Localtuya above v4.0.0 has connectivity issues where SmartLife app doesn't. Pretty much all devices.

### ISSUE THREAD

**Issue by FS1961** [rospogrigio/localtuya#1102]
## Environment

- Localtuya version: v4.0.0
- Last working localtuya version (if known and relevant): 
- Home Assistant Core version:  
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1. Use any version above 4.0.0
2. 
3.

## Configuration `configuration.yaml` or `config_flow`

```yaml
# Loads default set of integrations. Do not remove.
default_config:

zone: # Change default radius to 50
  - name: Home
    latitude: 49.5755337
    longitude: 7.4473159
    radius: 10
    icon: mdi:home

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

#Apple calendar
calendar:
  - platform: caldav
    url: https://caldav.icloud.com
    username: fspatt@XXXXXXX
    password: !secret apple_specific
    calendars:
      - XXXXXX
      - RHS SY2022-23
  - platform: worldclock
    name: Seoul
    time_zone: Asia/Seoul
    
bluetooth:
zha:
  custom_quirks_path: /config/custom_zha_quirks/
logger:
  default: warning
  logs:
    custom_components.localtuya: debug
    
```

## Provide Home Assistant taceback/logs

```txt
[ltuya.txt](https://github.com/rospogrigio/localtuya/files/9870824/ltuya.txt)

```
## Additional information

I've already changed WiFi channels but that seems to not really make a difference. Everything had been working fine for a long time and then I updated the version.

**Comment by FragMenthor** [comment]
Same here. For 2 days, downgrading to 4.0.2 seemed to work, but now I lose control of all my tuya devices randomly. Sometimes they appear as offline in HA, sometimes they don't, but I can´t control them from HA. Reloading the integration with the included service doesn't help, reloading from the UI either. Need to restart HA and then suddenly they are all functional. From SmartLife app they are always available... What is the matter with this, something on Tuya side? Something with the new HA version?

**Comment by besiktas97** [comment]
Versions above 4.0.2 are crappy and unstable as hell. I also did a downgrade for a long time ago to version 4.0.2 and everything is working good now.
I wont update until al those bugs are fixed.

**Comment by kuchara18** [comment]
I have the same problem.... Version 4.1.1. 

Any idea when this issue will be solved?

**Comment by SalazarPellicer** [comment]
Idem..With 4.1.1 lots of disconnections. with 4.0.2 it works better but some disconnection occurs

**Comment by FS1961** [comment]
Reading the documentation, I see the maintainer suggests using the Cloud API config. However, I cannot because the authentication fails for some reason.
<img width="1439" alt="Screenshot 2022-10-30 at 11 55 10 AM" src="https://user-images.githubusercontent.com/98458806/198874925-1d82a2b5-be2a-4c05-9be7-b6758948191b.png">

Not sure how to get around this and what do you put in the spot where it says "localtuya"?
<img width="481" alt="Screenshot 2022-10-30 at 11 58 11 AM" src="https://user-images.githubusercontent.com/98458806/198875076-98d585a6-733b-43cc-a60d-c05e955f629e.png">

**Comment by chuushi** [comment]
Even using the cloud integration API did not help me. I'm still getting lights randomly disconnected after 24 hours of uptime. I even tried ticking "Do not configure Cloud API account", but that didn't help.

The issue seems to occur after a slight disconnect when the DHCP lease gets renegotiated and renewed, even if it renews to the same IP. The lease originally expired in 12 hours, and devices went offline after 12 hours. When I tried DHCP reservation (which claims unlimited lease time), the devices stay connected for 24 hours, after which they all become unavailable.

All devices imaged here are light bulbs.
![image](https://user-images.githubusercontent.com/13530989/198919978-b646a461-9cc8-4e51-b0f8-957b0c17aa65.png)

I'm getting so frustrated with this issue, and even more so with the lack of organization of the stream of these duplicate issues.

**Comment by Pico1965** [comment]
Same for me.
My 26 Tuya device are online in Tuya app but unavailable in HA localtuya

**Comment by null-unknown** [comment]
I am facing also this issue with version 4.1.1..

**Comment by null-unknown** [comment]
I am also facing this issue with version 4.1.1...

**Comment by smarthomeIN** [comment]
I was facing same problem with 4.x versions. I downgraded to 3.5 version. The devices needed to be setup again but it was worth the hassle as now my devices are available. On 4.x the devices would become unavailable and reloading Integration or restarting HA didn't help.

HACS wasn't showing options below 4.0, I followed these steps:
1. Download device diagnostic info for each device. The downloaded file has the device id, local key, config (colour mode values, etc)
2. Run below in HA terminal: `mkdir /config/backup && mv /config/custom_components/localtuya /config/backup && mkdir /config/git && cd /config/git && wget https://codeload.github.com/rospogrigio/localtuya/zip/refs/tags/v3.5.0 && unzip v3.5.0.zip && mv localtuya-3.5.0/custom_components/localtuya /config/custom_components`
3. Remove old local tuya entry in Integrations
4. Restart HA
5. Add the devices again. All the config required is in the downloaded files from step 1. Note: In 3.5, add 1 local tuya integration for each device.

**Comment by FragMenthor** [comment]
I am really pondering that approach, really desperate right now, I must restart HA 2-3 times a day because of this. Restart solves for a while, and I can't automate restarts for a number of reasons: because not all devices become unavailable, and I can't have a measure of when to restart (situation that I shouldn't even consider, but I do), because automations are running and I stop them, because.... no :(... I really value the work put in to this, grateful to the developer in every way for almost 2 years. But I've grown so dependant on this that it is really not manageable anymore .. Has a desperate measure, I will probably try 3.x version, and if I can't manage to get the same, I will try the cloud integration '(

**Comment by FS1961** [comment]
I'm very much a novice but I thought I'd share what I've done to make things more stable.

1) Change WiFi channels (2.4 & 5Ghz) This includes the mesh antennae. 
2) Relocate ZHA coordinator and router
3) Turn band and router steering off of the WiFi router and mesh.

Everything has been stable for me for a few days now. The odd device goes offline for a bit and then cycles back online.

**Comment by AFumi39** [comment]
I try to add information here to see if this might help to identify the problem (for the developers).
In my house there're lot of interferences (many other wifi network that overlap each other), so (even if my wifi network is stable) every now and then there's an automatic channel switch if the interferences on current channel became too high.

As a result, there're "network issues" trying to reach the devices in those moments. Sometimes LocalTuya isa able to "recover" the device, but sometimes not. If it became unavailable (for LocalTuya, not for official Tuya app or integration), it doesn't go online again.
The only way to recover it is to "Reload" the integration or to restart HA.

I post examples of error that occurs, but that are not directly related to the issue (I think that the problem is not logged correctly)

```
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:707
Integration: LocalTuya (documentation, issues)
First occurred: 2 novembre 2022 09:14:53 (164 occurrences)
Last logged: 08:56:37

[410...441] Connect to 192.168.1.91 failed
[010...1ef] Connect to 192.168.1.107 failed
[bf2...6dh] Connect to 192.168.1.210 failed
[202...99c] Connect to 192.168.1.36 failed
[bfc...thi] Connect to 192.168.1.121 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 186, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 707, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.61', 6668)
```

```
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant
Source: custom_components/localtuya/discovery.py:67
Integration: LocalTuya (documentation, issues)
First occurred: 2 novembre 2022 09:31:33 (5 occurrences)
Last logged: 04:23:56

Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/config/custom_components/localtuya/discovery.py", line 65, in datagram_received
    data = decrypt_udp(data)
  File "/config/custom_components/localtuya/discovery.py", line 30, in decrypt_udp
    return _unpad(decryptor.update(message) + decryptor.finalize()).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 67, in datagram_received
    data = data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 0: invalid start byte
```

**Comment by BakaKawaii** [comment]
> I'm very much a novice but I thought I'd share what I've done to make things more stable.
> 
> 1. Change WiFi channels (2.4 & 5Ghz) This includes the mesh antennae.
> 2. Relocate ZHA coordinator and router
> 3. Turn band and router steering off of the WiFi router and mesh.
> 
> Everything has been stable for me for a few days now. The odd device goes offline for a bit and then cycles back online.

I have pretty stable WiFi and I can see the devices are connected to WiFi. I think for me it is because of the firewall rules that I have. I block internet to Tuya devices and HA. In 3.X I paused this firewall rule only when adding the device to local tuya so I wouldn’t get the error “connection succeeded but datapoints missing” but after adding the device to localtuya, I block them from internet again and everything is fine b/w reloads, restarts, etc. I think on 4.x it somehow tries to get the datapoints again but fails due to no internet.

**Comment by FS1961** [comment]
> > I'm very much a novice but I thought I'd share what I've done to make things more stable.
> > 
> > 1. Change WiFi channels (2.4 & 5Ghz) This includes the mesh antennae.
> > 2. Relocate ZHA coordinator and router
> > 3. Turn band and router steering off of the WiFi router and mesh.
> > 
> > Everything has been stable for me for a few days now. The odd device goes offline for a bit and then cycles back online.
> 
> I have pretty stable WiFi and I can see the devices are connected to WiFi. I think for me it is because of the firewall rules that I have. I block internet to Tuya devices and HA. In 3.X I paused this firewall rule only when adding the device to local tuya so I wouldn’t get the error “connection succeeded but datapoints missing” but after adding the device to localtuya, I block them from internet again and everything is fine b/w reloads, restarts, etc. I think on 4.x it somehow tries to get the datapoints again but fails due to no internet.

Have you tried "Configure" and remove "Reconfigure Cloud API account" and then select "Do not configure Cloud API account" ? Does this work for you?

**Comment by BakaKawaii** [comment]
I did not use cloud config. I got the local keys from iot.tuya.com a while back

**Comment by FS1961** [comment]
> I did not use cloud config. I got the local keys from iot.tuya.com a while back

Yes, but complete the above and see if there is a difference?!

Have you tried "Configure" and remove "Reconfigure Cloud API account" and then select "Do not configure Cloud API account" ? Does this work for you?

**Comment by BakaKawaii** [comment]
> > I did not use cloud config. I got the local keys from iot.tuya.com a while back
> 
> Yes, but complete the above and see if there is a difference?!
> 
> Have you tried "Configure" and remove "Reconfigure Cloud API account" and then select "Do not configure Cloud API account" ? Does this work for you?

I am on 3.x now. I never did the configure cloud API account on 4.x. I used the local keys I had already obtained.  4.x was a big change so maybe there are few bugs that still need to be fixed. I am sorry I can’t provide the required debug info.

**Comment by FS1961** [comment]
> > > I did not use cloud config. I got the local keys from iot.tuya.com a while back
> > 
> > 
> > Yes, but complete the above and see if there is a difference?!
> > Have you tried "Configure" and remove "Reconfigure Cloud API account" and then select "Do not configure Cloud API account" ? Does this work for you?
> 
> I am on 3.x now. I never did the configure cloud API account on 4.x. I used the local keys I had already obtained. 4.x was a big change so maybe there are few bugs that still need to be fixed. I am sorry I can’t provide the required debug info.

Just another user like you trying to help.

**Comment by chuushi** [comment]
> Turn band and router steering off of the WiFi router and mesh.

I think you are bringing up a good point. I have a Ubiquiti AP, hide my SSID, and have band steering turned on. The lights connect to WiFi successfully, but maybe that split second of disconnect during reconnection is enough to throw localtuya off while it attempts to reconnect with the light.

I will try creating a separate IoT SSID and have it work only on 2.4 GHz to see if that solves my issue.

**Comment by ManivannanBA** [comment]
Any help with the below error?

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:704
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 7:12:58 PM (1 occurrences)
Last logged: 7:12:58 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 580, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 245, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 704, in connect
    _, protocol = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.68.116', 6668)

**Comment by FragMenthor** [comment]
> I was facing same problem with 4.x versions. I downgraded to 3.5 version. The devices needed to be setup again but it was worth the hassle as now my devices are available. On 4.x the devices would become unavailable and reloading Integration or restarting HA didn't help.
> 
> HACS wasn't showing options below 4.0, I followed these steps:
> 
> 1. Download device diagnostic info for each device. The downloaded file has the device id, local key, config (colour mode values, etc)
> 2. Run in HA terminal: `mkdir /config/backup && mv /config/custom_components/localtuya /config/backup && mkdir /config/git && cd /config/git && wget https://codeload.github.com/rospogrigio/localtuya/zip/refs/tags/v3.5.0 && unzip v3.5.0.zip && mv localtuya-3.5.0/custom_components/localtuya /config/custom_components`
> 3. Remove old local tuya entry in Integrations
> 4. Restart HA
> 5. Add the devices again. All the config required is in the downloaded files from step 1.
>    Note: In 3.5, add a local tuya integration for each device; In 4.x, single local tuya integration handles multiple devices

Did this definitely solved the issues for you?

**Comment by BakaKawaii** [comment]
> Did this definitely solved the issues for you?
Yes. Very stable now like it always was

**Comment by FragMenthor** [comment]
Well, I'm on a "new" experience here, on 4.1.1 but removed my cloud credentials, and it seems stable now. Suggested by @FS1961 and it is stable for now.

**Comment by FS1961** [comment]
Well I've updated to Home-Assistant 11.1 and LocalTuya 4.1.1 and so far everything seems stable. I'm monitoring the situation and will see if I need to go back again. Removing the Cloud credentials, reconfiguring the WiFi, and turning off the router/band steering may have done the trick.

**Comment by FragMenthor** [comment]
Well, removing the cloud credentials didn't solve for me after all. Worked for a while, but during the night I had a failure that could not be recovered by localtuya, and all my tuya devices stayed offline for hours:

![image](https://user-images.githubusercontent.com/74264069/200274952-e8aaadf8-bf17-420c-9fe7-5e57954c0d99.png)

Reloading localtuya with the included service did not work, but a HA restart brought immediately all devices online.

**Comment by FS1961** [comment]
So does this mean it's a LocalTuya issue or HA?

**Comment by AFumi39** [comment]
> So does this mean it's a LocalTuya issue or HA?

Surely is LT issue, because if you reload the integration (without HA reboot), it starts to work again.
Also, with versions < 4.x it works flawlessly, so it's definitively a LT problem.

**Comment by FragMenthor** [comment]
I really don't know, but this is a recent behaviour. I had 4.x.x since the  beginning and this did not happen right after the upgrade, only a few weeks after (can't pinpoint dates or versions). Just wanted to know if there are any clues on what causes this, and if there a solution is beeing considered... @rospogrigio, could we get some feedback, please? Any hope of a solution on this? And thanks again for all your work!

**Comment by FragMenthor** [comment]
> > So does this mean it's a LocalTuya issue or HA?
> 
> Surely is LT issue, because if you reload the integration (without HA reboot), it starts to work again. Also, with versions < 4.x it works flawlessly, so it's definitively a LT problem.

For me nothing recovers unless I reboot HA. How do you reload the integration? Using the included service? That doens't work for me. And if I go to integrations, and reload in the "...", HA asks me to restart, so...

**Comment by AFumi39** [comment]
> For me nothing recovers unless I reboot HA. How do you reload the integration? Using the included service? That doens't work for me. And if I go to integrations, and reload in the "...", HA asks me to restart, so...

I tried both via service and via web menu (the "..." menu in the Integrations page) and works well for me.

**Comment by rospogrigio** [comment]
I personally don't have particular issues. It was very stable until 4.0.2, now I am getting very sporadic disconnections that are normally fixed with a reload of the integration (I have set up a handy button for that). 
4.1.0 brought big changes that could lead to instability and I know that @sibowler is trying to debug these situations.
I'm sorry but I really don't have any time now to look into this (I'm super overwhelmed at work) so either refer to him or  try to downgrade to the version that works best for all of you.
I don't see any real reason for why 4.0.x should introduce any instability since the core part is unchanged (only the cloud connection was introduced, and the re-organization of the devices), but 4.1.x is a big change and instabilities were expected.
Please share your feedbacks, thank you

**Comment by FragMenthor** [comment]
> I personally don't have particular issues. It was very stable until 4.0.2, now I am getting very sporadic disconnections that are normally fixed with a reload of the integration (I have set up a handy button for that). 4.1.0 brought big changes that could lead to instability and I know that @sibowler is trying to debug these situations. I'm sorry but I really don't have any time now to look into this (I'm super overwhelmed at work) so either refer to him or try to downgrade to the version that works best for all of you. I don't see any real reason for why 4.0.x should introduce any instability since the core part is unchanged (only the cloud connection was introduced, and the re-organization of the devices), but 4.1.x is a big change and instabilities were expected. Please share your feedbacks, thank you

Following your tip, I downgraded to 4.0.2. Seemed more stable for awhile, but then completly collapsed. I removed my credentials from the cloud connection and I'm not using it, so it should behave like 3.x, but it doesn't. I lost some of my deviced during the night and they did not recover until a full HA restart.

Chart of unavailable devices:
![image](https://user-images.githubusercontent.com/74264069/200542796-917f812c-d3b6-42ac-89f1-1212c5562829.png)
There was some recover, because I already have some automations to reset the internet router, and then reload HA, but did not solve all the problems during the night.

After I got up in the morning, I tryied reloading the integration 1 time with the included service: did nothing.

The second time I tryied it, after 5 minutes or so, I got this:
![image](https://user-images.githubusercontent.com/74264069/200542266-f6ceddc1-d9bf-4f77-bdd6-76b3586a88f9.png)

Then, in the integrations page, the reload option wasn't available, and required restart.
![image](https://user-images.githubusercontent.com/74264069/200542410-4f86f413-268a-4cd9-b0d1-337425dc85b6.png)

One of the logs:
```
Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/init.py:704
Integration: LocalTuya integration (documentation, issues)
First occurred: 05:02:31 (3240 occurrences)
Last logged: 07:54:21

[557...c4b] Connect to 192.168.1.75 failed
[371...cce] Connect to 192.168.1.70 failed
[bf9...ja0] Connect to 192.168.1.93 failed
[bf6...q1b] Connect to 192.168.1.102 failed
[bf7...7fk] Connect to 192.168.1.102 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 186, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/init.py", line 704, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionResetError: [Errno 104] Connect call failed ('192.168.1.70', 6668)
```
This is really bugging me a lot... :/ :(

**Comment by rospogrigio** [comment]
Are you sure you are not having connectivity issues? Do the devices work in the SmartLife/Tuya app? 
Some devices require the app not to be open to operate locally.
And what happens if you roll back to localtuya 3.5.0?

**Comment by AFumi39** [comment]
@rospogrigio
Similar to what @FragMenthor wrote above, until 4.0.2 it was very stable. After the upgrade to 4.1 (maybe is just a coincidence) the problems popped-up and the devices started to become unavailable after some hours. Strangely downgrading to 4.0.2 didn't solved the issue (now I come back to 4.1).
So, I have (at least daily) to reload the integration. That's a bit frustrating (I'm planning to write an automation that invoke the reload service automatically) because it seems that there's no log regarding the error/exception when the devices become unavailable.
Also, downgrading to 3.x means delete and add again al the devices, so I don't want to do it (and there're some deprecated methods that will stop working soon).


PS: comunque grazie per tutto il lavoro che fate e l'impegno che ci mettete, le tante segnalazioni sono indice di quanta gente utilizza questo fantastico componente. ❤

**Comment by FragMenthor** [comment]
> Are you sure you are not having connectivity issues? Do the devices work in the SmartLife/Tuya app? Some devices require the app not to be open to operate locally. And what happens if you roll back to localtuya 3.5.0?

I may have some connectivity issues, probably because sometimes the devices change wifi from the main router to an ap (in ap mode, same SSID, just an extender), but that should not be an issue because in the Smartlife app they are always available; I only use the app as an ultimate desperate resource, when I can't control the devices from HA. The devices never change localkey.
Still don't know what happens if I roll back to 3.5, but if this can't be sorted out I will try to do that. Lots of work envolved, because some devices (total 24) that I used since the beggining don't have entity_ids according to device ID, so I must do 1 by 1 (begginer logic that stayed through the years, since it was working... now a pain in... the back)

**Comment by smarthomefamilyverrips** [comment]
Same problems here

**Comment by FragMenthor** [comment]
As a daily log of my attempts on understanding what is going on, last night thinks did not go as bad as usual, only one of my Tuya devices did not recover:

Chart of offline devices, 24h:

![image](https://user-images.githubusercontent.com/74264069/200793570-73a65597-16da-45ea-8a27-f4fdb36e3475.png)

Offline dual switch module:

![image](https://user-images.githubusercontent.com/74264069/200793969-8f4e77a4-21c7-494a-883f-fb5805b494ce.png)

I can ping the device and it responds very fast:

![image](https://user-images.githubusercontent.com/74264069/200793073-216433b7-8fe5-4748-94cd-4f1ae0cc6f29.png)

I can control it from the Tuya app:

![image](https://user-images.githubusercontent.com/74264069/200794233-ee35e0d3-faba-4f60-9009-207fa05256d2.png) 
![image](https://user-images.githubusercontent.com/74264069/200794320-8dbdeac5-c793-4cc2-939b-62758e742460.png)

The only log that I have about this device, is at the time it was reported offline. 
```
2022-11-09 06:33:45.252 ERROR (MainThread) [custom_components.localtuya.common] [371...cce] Connect to 192.168.1.70 failed
OSError: [Errno 113] Connect call failed ('192.168.1.70', 6668)
```
No more references to this device during the 3 hours after in the logs, it seams it was "abandoned" by localtuya and no more retries where made to try to fetch it's status.

It stays offline in HA. Any thought on what I could do to try to "force" this in HA without restarting? Reloading by service does not solve.
I'm now testing on 4.0.2 with HA 2022.11.2

**Comment by AFumi39** [comment]
It seems a little more stable with 4.1 and disabling Cloud integration, but after about 24 hours a device become unavailable (often the same device).
I just added an automation that reload the integration when that device goes offline for 5 minutes. we'll see.

Just as @FragMenthor says, at given point (not always) when that error appears, LocalTuya don't try to connect to the device anymore (so HA mark it as unavailable).

**Comment by FS1961** [comment]
I have completely stabilized my system.  I am @ ver4.0 with the router changes I made recently removing the band and router steering and the wifi channel change. Although I have the odd "toggle", it is only momentary. Based on @rospogrigio's suggestion, I also suggest to back down to 4.0 and just wait.  

Just my 2¢ worth.

**Comment by FS1961** [comment]
I also recently moved my Zigbee router and now everything is completely stable on 4.0. I guess there is an issue with Zigbee and 2.4Ghz overlapping each other. I am using ZHA which makes it complicated to change Zigbee channels.  Again, just interesting factoids, not sure if it's an actual "fix" but I have heard that Zigbee/Zwave and WiFi 2.4Ghz can conflict.

**Comment by rospogrigio** [comment]
I don't know what to say. I'm on the latest release and it's very stable in my setup, with no particular setting on the router. I do have a switch that loses connection but it happens also in the app, I believe it has a weak antenna. So it's really hard to understand why some people experience these problems and how to fix them.

**Comment by FS1961** [comment]
I loaded 4.1.1 and am monitoring. Will advise.

**Comment by FS1961** [comment]
At least for me, this seems fairly stable. I still have two devices that are "cycling" between available and not available. If I restart "localtuya," it seems to fix it. I guess this is working for the most part. I'm going to give it few more days and then will update.

**Comment by FS1961** [comment]
So after a few days, it would appear that the same devices are the troublesome ones - 4 out of 16 devices, 25%! Only 2 of the devices are exactly the same, WiFi light bulbs. The other two have a working twin. For instance - I have a plug that works and 1 that toggles available/unavailable. Here are my devices. The "kitchen" lights are the same devices, the "Entry Lamp" and "Floor Lamp" are the same type, and the "Dining" and "Schrank" strips are the same. Why 1 works and not the other at v4.1.1 versus all working at v4.0 makes no sense to me!

![IMG_0395](https://user-images.githubusercontent.com/98458806/201591597-d8c1c56e-9877-463c-8a00-f06abb86d771.jpeg)

**Comment by AFumi39** [comment]
I tried to downgrade to 4.0.2, but after some time (about 24 hours) the devices (mostly the same devices, but sometimes other) starts to become unavailable.
I didn't try to delete all devices and the integration and add all again, because I have 20 devices with many entities and is difficult to configure all correctly on the first try (otherwise I have to delete the integration and add all again for any mistake!).

**Comment by osnwt** [comment]
And that's another question why yaml configuration was completely removed... Just to remind.

**Comment by AFumi39** [comment]
I noticed something that's a bug with versions 4.1 that is ok with 4.0.2:
when the integration starts (after reboot or integration reload) often I have a wrong value from a DPS of a device, with the first read (the following readings are ok). Maybe the problem is with all the DPS or devices, but I notice this one because is the main energy meter of my house and the daily counter (that only add) miscalculate and give me wrong values for all day.
With 4.0.2 all the readings are ok (or maybe the incorrect readings are ignored.

**Comment by rospogrigio** [comment]
This is really interesting. Maybe @sibowler can investigate the matter...

**Comment by AFumi39** [comment]
This is an example (I use the 4.0.2 again, now; I'm monitoring the situation), as you can see the problem is not every day, but related to the restarts (I think), but only with 4.1, not with previous versions.
![LT_energy_counter](https://user-images.githubusercontent.com/85888564/201880867-905a578c-c516-4ce4-8146-336f52c018b7.png)

**Comment by AFumi39** [comment]
After almost 3 days, I can say that if you downgrade from 4.1 to 4.0.2, you have to reboot 2 times. I don't know why, but after the 2nd reboot it became stable again.
So, @rospogrigio was right: the changes in 4.1 made LT more unstable and susceptible to every little network communication issue.

**Comment by sibowler** [comment]
@AFumi39 - Is the above graph with v4.1.0 or v4.1.1? Some of the changes introduced in 4.1.0 seemed to cause some devices to behave strangely and/or turn unresponsive. 4.1.1 then made these changes dormant unless enabled. If you've not tried 4.1.1 then it would be worth a change to see if you see the same incorrect DPS values.

**Comment by AFumi39** [comment]
@sibowler 
I don't remember if the misreading of 5th of November was 4.1.1 or 4.1.0, but surely the others (11-12th) were with 4.1.1

Until now, after almost 4 days until the 2nd reboot with 4.0.2, no issue at all: no misreadings and no unavailable devices (with 4.1.x there was at least 1 offline device in 24 hours at most).

**Comment by Zeunas** [comment]
Same. 4.0.2 is working flawlessly for me.

**Comment by FS1961** [comment]
Same. Can't move forward.

**Comment by SalazarPellicer** [comment]
Here same with 4.0.2. However, after almost a week without problems, tonight all devices have become unavailable. Once restarted HA, everything is solved

**Comment by besiktas97** [comment]
> Here same with 4.0.2. However, after almost a week without problems, tonight all devices have become unavailable. Once restarted HA, everything is solved

Got exactly the same issue last night. Every device was unavailable and after a restart everything was working again. I am using local tuya version: v4.0.0. In all other versions above v4.0.0. I am having issues with connection lost and unavailable like last night.

**Comment by AFumi39** [comment]
Yesterday I had a connection problem for few minutes (as I said before, unfortunately there're lot of interferences and issue happens), ant today morning the same.
With 4.0.2 the devices reconnected automatically with no misreadings at all

![LT_energy_counter_2](https://user-images.githubusercontent.com/85888564/202696757-1359f9f2-2c60-438d-907f-f3bec4c2c0e6.png)

**Comment by FS1961** [comment]
So is ANYONE using 4.1.x without issues? If not, should it be removed and just wait until it's fixed?

**Comment by rospogrigio** [comment]
I am. Every time I have unavailable devices it's because they are actually having connectivity problems, also in the SmartLife app. So maybe it depends on the type of devices? I only own switches and covers, all are using 3.3 protocol. How about you @AFumi39?

**Comment by AFumi39** [comment]
Those are my devices. Most of them are Smart Socket (metered), 2 switches, 1 strip, 1 energy meter.
That's all

![LT_devices](https://user-images.githubusercontent.com/85888564/203494564-16c806e7-596e-4289-9153-c50361532ad6.png)

**Comment by rospogrigio** [comment]
And which of these were having problems with 4.1.x? All of them? Or only some?

**Comment by AFumi39** [comment]
All of them. Some more frequently, some less, but there's no apparent reason. For example often the BW-SS5 "Luce Bagno", almost never BW-SS5 "Sala Cucina".
More frequently unavailabilities are with "Luce Bagno", "Asciugatrice" and "Dyson", but sometimes are other devices. What's strange is that, for example, "Asciugatrice" (BW-SHP10) have frequently problems (with 4.1.x), but "Lavatrice" (same model, almost in the same position, few cm away) not so much.

So, I think the problem isn't with the specific device, but with the configuration (or the order) in LT. The only thing that I didn't try so far is upgrade from 4.0.2 to 4.1.1 with Cloud disabled. I swear I'll try as soon as I have time.

**Comment by patrik-malina** [comment]
I have latest LT (with cloud account enabled) and HA versions.
28 devices (switches, plugs, meteres, covers, garage door, valve, thermostat, siren) 
Also have orginal tuya integration (34 devices) with disabled (28) devices in LT, but must have for smoke, gas and water sensors. 
Everithing works as should, sort of. 
There are unavialable states for all devices, but they last few seconds and then for hours everithing is ok. This is unnoticeable, except if you looking in history log. 
I spent lots of hours to find right settings for AP to get most stabile network. 
Using unifi A6lite AP with following settings:
Channel 2, width 20mhz. This works best with me, but could be different for others. 
I would suggest to disable Band steering, and set channel width to 20mhz and play with channels.

**Comment by BrettEBowman** [comment]
> @patrik-malina I would agree with you, but if I've unavailability problems with 4.1.x that are not present with 4.0.2... that means that the AP is not the problem, in my case.

That isn't necessarily true. I may be that there are (subtle?) changes in 4.1.x that affect how LocalTuya handles device changes--particularly when they switch from one wifi AP to another, when the AP changes the channel automatically, etc. Since there have been multiple reports from people indicating that their situation improved if they made changes to their wifi configuration, it does seem like it is somehow related.

@rospogrigio: Since you do not seem to be experiencing these problems, I'm guessing that you only have a single wifi AP (either a router or a standalone AP). And that you also don't have band steering available/enabled. Is that correct? Is the wifi SSID that you use for your Tuya devices only available on the 2.4GHz band and only on a single AP device? And is the 2.4GHz set for only a 20MHz channel size?

I do think that it would be interesting to see if the updated TinyTuya with protocol v3.4 support would handle wifi connection changes any better.

**Comment by rospogrigio** [comment]
Oooh yes you are right @BrettEBowman . Should it be related to that, the problem might be in the "state restoring" part of the code. Maybe this can be a hint for @sibowler to debug.

Regarding my configuration: yes, I do have a single AP but I also have a range extender that we use occasionally (only when my GF is having online meetings from the bedroom) and it never messed up things when being switched on. I should check because I never changed the settings but I believe that ,as you say, I should be using 2.4GHz only, I'm not sure about the channel, it should be 6 or 7 maybe. I'll check and let you know.

May I suggest some of you who have repeatable behavior (such as: all ok with 4.0.x, all messed up with 4.1.x) to comment or apply blocks of code gradually until you detect which is the part of the code that introduced the problems? For git users, you can see the differences with the command  `git diff 2bae03c679a24525def2bdb0a2999530aefa68e4`. It would be of great help to debug.

**Comment by sibowler** [comment]
I've also hit issues with unavailable devices when my wifi signal was weak - and the failures weren't t always consistent. To identify that it was a wifi issue, i ran a ping every second over a day period and looked for any drops - if the wifi connection is stable you shouldn't see any drops.

It's possible that something in the connectivity that changed after 4.0.x meant that these connection drops are detected quicker than previously... _Maybe_ the connection was essentially lost in 4.0.x but not detected as AFAIK we detect drops from a failed send to the device.

To help with debugging, try the ping thing, and also add the following to your configuration.yaml in the logs section:
```
    custom_components.localtuya.pytuya: debug
    custom_components.localtuya: debug
```
i.e.:
```
logger:
  default: warning
  logs:
    custom_components.localtuya.pytuya: debug
    custom_components.localtuya: debug
````

Like @rospogrigio, I haven't hit this issue (except where my wifi was weak - which has now been fixed for that device using a repeater) - if I had it would be a lot easier to debug/fix.

**Comment by IceBotYT** [comment]
This worked for me. Apparently the issue was the lights involved with the issues had bad connection, so I did the following on the Smart Life app:

1. Go to the offending device.
2. Click the edit icon in the top right corner
3. Scroll down and click "remove device"
4. Choose "disconnect & wipe data"
5. Choose confirm
6. Set up the light as new but with a different Wi-Fi network

**Comment by xkuizit** [comment]
I have also run into issues since updating from 3.x to 4.x. 5.x was a disaster so moved down to 4.0.2 as a happy medium so that I wouldn't have to setup all my devices again. My logs are littered with my localtuya devices going unavailable roughly every 45 minutes. In most cases for less than 60 seconds, but at least a few times a day for over a minute. In 4.0.2 they seem to always come back online eventually, so I can make do for now. In 5.0.0 they would periodically go unavailable and never come back without a localtuya reload and eventually would require HA restart. 

Have done a few things to debug this a bit.

1. I setup a ping test to just ping my outlet device once a second. Ran this for a couple days with no packet loss. So connectivity is not the problem I'm having. 
2. I setup tinytuya on a docker instance and ran the monitoring example they have on their github doc page (https://github.com/jasonacox/tinytuya). What I noticed is that every once in a while the device misses a heartbeat. However, the device is still connected and the next heartbeat comes through just fine. In the short tests I ran it was always a single heartbeat missed roughly every 45 minutes.
3. The missed heartbeats in tinytuya correlated with localtuya setting the device to unavailable. However the difference is that localtuya seems to treat this as the worst case, forces a socket disconnect, and starts a reconnection to the device. This seems to take a minimum of 30 seconds but in many cases can be as much as 90+ seconds. 

@rospogrigio @sibowler have you considered migrating from pytuya (hasn't been maintained for years) to tinytuya (a fork that is still actively maintained)? The connection handling in tinytuya seems to be much more robust in the minimal testing I did. For instance instead of relying on exceptions, tinytuya uses json error codes in many cases for more graceful handling. It handles the hiccup of the missed heartbeat without requiring any additional coding. In fact it even handled the case where I kicked the device off of my wifi and then allowed it back on. This would be a case where you'd want localtuya to report the device as unavailable, but I was impressed that tinytuya was able to keep the socket persistent and picked up the heartbeat monitoring right away. pytuya seems to do a full disconnect / reconnect dance here which seems to extend the time for getting running again.

**Comment by rospogrigio** [comment]
@xkuizit I have nothing against it but I'd like to check, since pytuya should have a "push" mechanism that should make the transmission of events faster and as a consequence make the system more responsive. But this is something we'd need to check.
In the meantime, I have been working in trying to make the system more stable, by catching exceptions properly and also found some reasons why sometimes devices would disconnect and not reconnect any more. Maybe you could try this PR and tell me if you find it to be more stable? It's PR #1276 .
Let me know how it goes, thank you

**Comment by xkuizit** [comment]
@rospogrigio I tried out the PR. It is certainly more stable than 5.0.0. Since installing this morning I haven't run into the case where it completely fails and requires restart of HA. Will keep it running longer as I may still run into it after a couple days. 

I am still getting the timeouts roughly every 40 mins. 

```
Command 9 timed out waiting for sequence number -100
Disconnected - waiting for discovery broadcast
```

Seems to take 30-40 secs or so to re-establish a connection. This is consistent with what I was seeing in 4.0.2. 

I noticed that in the original "Trying to connect..." message to "Successfully connected..." is on the order of 2 seconds. But each time it gets disconnected there is about a 20 second gap from "Disconnected - waiting for discovery broadcast" to "Trying to connect..." Then there is an additional 10 seconds before "Successfully connected..." So re-connections are way slower than original connections. 

I'm also noticing that periodically I get a failure to connect error.

`Failed to connect to 192...27: [Errno 113] Connect call failed`

But I think the primary issue is the forced re-connects due to missed heartbeats roughly every 40 mins. I'm monitoring 4 different devices that are on 3 different APs and 2 different LANs and yet the missed heartbeats are synchronized (down to the second).

[tuya_out6.log](https://github.com/rospogrigio/localtuya/files/10679773/tuya_out6.log)

**Comment by kastmgnru** [comment]
Every time the wifi network changes channel, the devices are disconnected for 1 minute and then reconnected. It would be nice if the connection was stable and not lost when changing the wifi channel.

**Comment by FS1961** [comment]
> @kastmgnru - I had this issue until I found a steady WiFi channel. Try locking router/band steering and see if this helps you.
