### ISSUE TITLE
YAML config flow seems to not be working any more

### ISSUE THREAD

**Issue by codingcatgirl** [rospogrigio/localtuya#687]
## The problem

Since localtuya doesn't discover my smart plug's DPS on power usage, i tried to configure localtuya using the configuration.yml instead of the config flow instead. However, after doing so and restarting home assistant, the loyaltuya integration doesn't show up in the list of active integrations and no devices or entities that have been set up can be shown in the respective configuration pages either. This happens even if i only configure it as a switch with no power consumption, with precisely the same settings that work through the config flow.

Interestingly, while no devices or entities are added, localtuya doesn't completely ignore the YAML settings. This can be seen when trying to add a localtuya device via the config flow. In the first screen, the list of discovered devices, after the device id, the IP address is no longer shown (as it is with unconfigured devices) but instead the name i configured in the YAML is shown. So, the device seems to be configured internally in localtuya in some way, but not be exposed to home assistant as devices/entities. 

## Environment

- Localtuya version: 3.3.0
- Home Assistant Core version: 2021.12.7
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce
1. Configure a tuya smart plug (or, possibly any device) using the YAML configuration, as shown below.
2. Restart
3. Look at the integrations/devices/entities lists.

## Configuration `configuration.yaml` or `config_flow`

```yaml
localtuya:
  - host: 192.168.178.99
    device_id: (as discovered through the config flow)
    local_key: (as determined through the usual means, the key is confirmed to be working when used in the config flow, the switch can be controlled)
    friendly_name: "abcdefg"
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: "hijklmnop"
        id: 1
```

## Provide Home Assistant taceback/logs
I'd like to set the log level to debug, but the method described in the issue template does not work for me. There seems to be no service named logger.set_level.

**Comment by jeremysherriff** [comment]
Debug should be achieved by adding the following lines to configuration.yaml:
```
logger:
  default: warning
  logs:
    custom_components.localtuya: debug
```

I haven't checked what the issue template says but this is copied directly from my own config.

**Comment by codingcatgirl** [comment]
Thanks for the hint! Sadly, nothing useful seems to be brought to light by it on this issue. 

```
2022-01-02 20:09:23 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.178.21', 'gwId': 'bf802a379e0900ae3eakkt', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwtgrcsf3hxng', 'version': '3.3'}
2022-01-02 20:09:23 DEBUG (MainThread) [custom_components.localtuya.discovery] Listening to broadcasts on UDP port 6666 and 6667
2022-01-02 20:09:23 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.178.99', 'gwId': 'bf08d3a7087ecab2c7uxpp', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwtgrcsf3hxng', 'version': '3.3'}
2022-01-02 20:09:27 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.178.21', 'gwId': 'bf802a379e0900ae3eakkt', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwtgrcsf3hxng', 'version': '3.3'}
2022-01-02 20:09:28 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.178.99', 'gwId': 'bf08d3a7087ecab2c7uxpp', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwtgrcsf3hxng', 'version': '3.3'}
2022-01-02 20:09:32 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.178.21', 'gwId': 'bf802a379e0900ae3eakkt', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwtgrcsf3hxng', 'version': '3.3'}
2022-01-02 20:09:33 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.178.99', 'gwId': 'bf08d3a7087ecab2c7uxpp', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwtgrcsf3hxng', 'version': '3.3'}
2022-01-02 20:09:37 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.178.21', 'gwId': 'bf802a379e0900ae3eakkt', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwtgrcsf3hxng', 'version': '3.3'}
2022-01-02 20:09:38 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.178.99', 'gwId': 'bf08d3a7087ecab2c7uxpp', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwtgrcsf3hxng', 'version': '3.3'}
2022-01-02 20:09:42 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.178.21', 'gwId': 'bf802a379e0900ae3eakkt', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwtgrcsf3hxng', 'version': '3.3'}
2022-01-02 20:09:43 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.178.99', 'gwId': 'bf08d3a7087ecab2c7uxpp', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwtgrcsf3hxng', 'version': '3.3'}
2022-01-02 20:09:47 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.178.21', 'gwId': 'bf802a379e0900ae3eakkt', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwtgrcsf3hxng', 'version': '3.3'}
2022-01-02 20:09:48 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.178.99', 'gwId': 'bf08d3a7087ecab2c7uxpp', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwtgrcsf3hxng', 'version': '3.3'}

**Comment by jeremysherriff** [comment]
Did this cover the period where you attempted to add one of the devices via the config_flow gui? If not, can you try that and see if something else is captured?

**Comment by jeremysherriff** [comment]
You mention returning to localtuya, does that mean that the official tuya integration was being used earlier?  I wonder if there are some ghost entries in your HA config that are claiming the devices.

Assuming you have the SSH add-on installed, can you check the files `core.config_entries`, `core.device_registry` and `core.entity_registry` in `/config/.storage/` to see whether there are remnants of entities?  Something like 
```
➜  ~ cd /config/.storage
➜  .storage grep 52547183500291114b68 core.*
core.config_entries:                    "device_id": "52547183500291114b68",
core.config_entries:                "unique_id": "52547183500291114b68",
core.device_registry:                        "local_52547183500291114b68"
core.entity_registry:                "unique_id": "local_52547183500291114b68_1",
core.entity_registry:                "unique_id": "local_52547183500291114b68_19",
```
should do it, but you might want to play with different grep expressions.

If you do find remnants, I think you're going to need to edit the files and remove the entities, then restart HA.

**Comment by codingcatgirl** [comment]
No, i didn't use the official tuya integration in between. Since i mainly want to use the plugs for power consumption monitoring i just didn't use them in the meantime. 

I tried the config flow, and the first thing i saw was "Connection to device successful, but no DPs were found" or something along those lines, so it found no DPs at all. I had unplugged the smart plug earlier, so this is likely why. After pressing the manual switch on the smart plug and retrying, the error message disappeared. Makes me think that some magic needs to happen for localtuya to request datapoints to "appear".

```
[sadly can't see all and but this was repeated a few times:]

[custom_components.localtuya.pytuya] [bf8...kkt] Waiting for sequence number 5
[custom_components.localtuya.pytuya] [bf8...kkt] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b"3.3\x00\x00\x00\x00\x00\x003\xe7\x00\x00\x00\x01i\x03(\xae#\x99'\xce\x99ve\xde\xf2\xac[p\rXf\xe9\x19Z\xa5G\xccdN\xaf\xbc\xb0\xfdm", crc=1319597256)
[custom_components.localtuya.pytuya] [bf8...kkt] Got status update
[custom_components.localtuya.pytuya] [bf8...kkt] Decrypted payload: {"dps":{},"t":6771}
[custom_components.localtuya.pytuya] [bf8...kkt] Dispatching message TuyaMessage(seqno=5, cmd=13, retcode=0, payload=b'', crc=4036118812)
[custom_components.localtuya.pytuya] [bf8...kkt] Dispatching sequence number 5
[custom_components.localtuya.pytuya] [bf8...kkt] Decrypted payload: {}
[custom_components.localtuya.pytuya] [bf8...kkt] Detected dps: {}
[custom_components.localtuya.pytuya] [bf8...kkt] Closing connection
[custom_components.localtuya.pytuya] [bf8...kkt] Stopped heartbeat loop
[custom_components.localtuya.pytuya] [bf8...kkt] Connection lost: None
[custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.178.21', 'gwId': 'bf802a379e0900ae3eakkt', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwtgrcsf3hxng', 'version': '3.3'}
[custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.178.21', 'gwId': 'bf802a379e0900ae3eakkt', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwtgrcsf3hxng', 'version': '3.3'}
[custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.178.21', 'gwId': 'bf802a379e0900ae3eakkt', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwtgrcsf3hxng', 'version': '3.3'}
[custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.178.99', 'gwId': 'bf08d3a7087ecab2c7uxpp', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwtgrcsf3hxng', 'version': '3.3'}
[custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.178.21', 'gwId': 'bf802a379e0900ae3eakkt', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwtgrcsf3hxng', 'version': '3.3'}
[custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.178.99', 'gwId': 'bf08d3a7087ecab2c7uxpp', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyqwtgrcsf3hxng', 'version': '3.3'}

[restarted the config flow at this point]

[custom_components.localtuya.pytuya] [bf8...kkt] Started heartbeat loop
[custom_components.localtuya.pytuya] [bf8...kkt] Sending command heartbeat (device type: type_0a)
[custom_components.localtuya.pytuya] [bf8...kkt] Send payload: b'{}'
[custom_components.localtuya.pytuya] [bf8...kkt] Waiting for sequence number -100
[custom_components.localtuya.pytuya] [bf8...kkt] Sending command status (device type: type_0a)
[custom_components.localtuya.pytuya] [bf8...kkt] Send payload: b'{"gwId":"bf802a379e0900ae3eakkt","devId":"bf802a379e0900ae3eakkt"}'
[custom_components.localtuya.pytuya] [bf8...kkt] Waiting for sequence number 1
[custom_components.localtuya.pytuya] [bf8...kkt] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
[custom_components.localtuya.pytuya] [bf8...kkt] Got heartbeat response
[custom_components.localtuya.pytuya] [bf8...kkt] Decrypted payload: {}
[custom_components.localtuya.pytuya] [bf8...kkt] Dispatching message TuyaMessage(seqno=1, cmd=10, retcode=0, payload=b'\xd2\x81\x12\x8a\xd6\x8e\xb9\x1d\x88\x0e\x1f\xaf\r(\x8f\x9c\xc9^)\xd6\x8c\xa1u\xd9\xac\xcbN\xd8\xa2\xe6\xc1"', crc=4289267958)
[custom_components.localtuya.pytuya] [bf8...kkt] Dispatching sequence number 1
[custom_components.localtuya.pytuya] [bf8...kkt] Decrypted payload: {"dps":{"1":false,"9":0}}
[custom_components.localtuya.pytuya] [bf8...kkt] Closing connection
[custom_components.localtuya.pytuya] [bf8...kkt] Stopped heartbeat loop
[custom_components.localtuya.pytuya] [bf8...kkt] Connection lost: None
```

**Comment by jeremysherriff** [comment]
The DPS discovery routine isn't returning anything:
```
[custom_components.localtuya.pytuya] [bf8...kkt] Detected dps: {}
```

Have you tried turning the switch off at the mains power (or remove the switch from the power socket I guess)?  It looks to me like it's a local fault although I can't imagine how that affects multiple devices.  Make sure you have actively killed the app on your phone too (not just returned to home screen).

**Comment by codingcatgirl** [comment]
Yes, can you please read what i wrote? ^^

Quote:
> I tried the config flow, and the first thing i saw was "Connection to device successful, but no DPs were found" or something along those lines, so it found no DPs at all. I had unplugged the smart plug earlier, so this is likely why. After pressing the manual switch on the smart plug and retrying, the error message disappeared. Makes me think that some magic needs to happen for localtuya to request datapoints to "appear".

**Comment by jeremysherriff** [comment]
Ah, my apologies I focused more on the "pressing the manual switch" part.

Perhaps if you revert to the older version of the integration and see whether the behaviour remains?  There was an edit in PR #549 that deliberately drops data that is the same as the previous data (to reduce database bloat) but I don't think it would cause the behaviour you are describing.

If you can define the devices successfully in the older version, hopefully you'll then be able to update to the newer version and add a value for the data refresh, to get the functionality you need.

Unfortunately I can't reproduce the same behaviour here so I'm running out of capability to help.

**Comment by Elendilon** [comment]
@codingcatgirl Is your tuya device disconnected from the internet when doing these tests? If so, you are likely hitting an issue where the device sits in a zombie mode after power off/on (and one of the ways devices respond while like this is with a successful, but empty, dps response). If this is the case I have a PR to fix it, but I need to update it to sit on top of the other updatedps PR that just went in (and also fix some more weird ways other devices have been shown to respond).

If not, then it is likely a second issue where type_0a devices respond with an empty, but otherwise valid response when we actually need to be using the other mode. I also fixed that incidentally at one point (by considering an empty status response an error), but unfortunately there are also valid reasons we can get back an empty status response so it needs to be considered an error/try a type switch only during connection; which is a bit hard with the way the code is currently laid out. As such, this one may require a bit more time.

**Comment by codingcatgirl** [comment]
@jeremysherriff Do you have a smart socket with power consumption data as well? In that case, hmm…

@Elendilon oh, interesting! yes, my tuya devices are disconnected from the internet. I was aware of this issue (or a similar one?), but since it didn't become fully unresponsive (after pressing the physical button once i can turn it on and off via home assistant after all) i didn't think i was affected. But yeah that sounds like your PR (#491, for reference if anyone is wondering) might fix it. I have subscribed to it and am looking forward to seeing it merged then :)

**Comment by codingcatgirl** [comment]
@Elendilon What you replied is probably more relevant to #688 btw :D Not to this issue, which is aboutt he YAML configuration not working.

**Comment by Elendilon** [comment]
Not sure about the YAML config, but in the config flow log pasted above where during initialization you get empty DPS, and then after pressing the button only get the on/off DPS - that is probably the device being in "zombie mode".

**Comment by codingcatgirl** [comment]
Yes, i know. I mentioned that the reason i used the YAML config was because i hoped i could circumvent this issue (i mentioned it in the first post) but then noticed the YAML config doesn't work at all. i've posted a reference to this in #688 so people will know to look forward to your pull request.

The YAML problem remains unsolved still though. Even though i hope i won't need it once the PR is merged, the YAML configuration still should work right now.

**Comment by jeremysherriff** [comment]
> @jeremysherriff Do you have a smart socket with power consumption data as well? In that case, hmm…

@codingcatgirl yeah I have three devices with energy monitoring, and have been running v3.3.0 as beta code for a couple of months.  I have three of [these](https://www.kogan.com/nz/buy/kogan-smarterhome-smart-plug-energy-meter-5v-24a-usb-ports/) smart sockets.

> The YAML problem remains unsolved still though.

You're right, we haven't really focused on that aspect.  Can you restart home assistant with the YAML localtuya config and the logger/debug stuff both in place, and then grab the (relevant) content of /config/home-assistant.log that shows the integration load and the first few attempts to get data from the devices (if it does in fact attempt to do so)?

We don't need the scan_interval bit in place for this, up to you whether you include it in your config or not.

You won't be able to grep the log as we need any python errors that get thrown.  Logs from the integration and one of my devices included below for comparison.
```
2022-01-04 08:36:52 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration localtuya which has not been tested by
Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
...
2022-01-04 08:36:56 DEBUG (MainThread) [custom_components.localtuya.discovery] Listening to broadcasts on UDP port 6666 and 6667
2022-01-04 08:36:56 DEBUG (MainThread) [custom_components.localtuya.switch] [525...12b] Adding switch.office_plug_switch with configuration: {'friendly_name': 'Office Plug Switch', 'current_consumption': 19, 'current': 18, 'id': 1, 'platform': 'switch'}
...
2022-01-04 08:36:58 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.220.115', 'gwId': '5254718350029112012b', 'active': 2, 'ability': 0, 'mode': 0, 'encrypt': True, 'productKey': 'keyjcr45yfptp7h7', 'version': '3.3'}
2022-01-04 08:36:58 DEBUG (MainThread) [custom_components.localtuya] Device 5254718350029112012b found with IP 192.168.220.115
2022-01-04 08:36:58 DEBUG (MainThread) [custom_components.localtuya.common] [525...12b] Connecting to 192.168.220.115
2022-01-04 08:36:58 DEBUG (MainThread) [custom_components.localtuya.pytuya] [525...12b] Started heartbeat loop
2022-01-04 08:36:58 DEBUG (MainThread) [custom_components.localtuya.pytuya] [525...12b] Sending command heartbeat (device type: type_0a)
2022-01-04 08:36:58 DEBUG (MainThread) [custom_components.localtuya.pytuya] [525...12b] Send payload: b'{}'
2022-01-04 08:36:58 DEBUG (MainThread) [custom_components.localtuya.pytuya] [525...12b] Waiting for sequence number -100
2022-01-04 08:36:58 DEBUG (MainThread) [custom_components.localtuya.common] [525...12b] Retrieving initial state
2022-01-04 08:36:58 DEBUG (MainThread) [custom_components.localtuya.pytuya] [525...12b] Sending command status (device type: type_0a)
2022-01-04 08:36:58 DEBUG (MainThread) [custom_components.localtuya.pytuya] [525...12b] Send payload: b'{"gwId":"5254718350029112012b","devId":"5254718350029112012b"}'
2022-01-04 08:36:58 DEBUG (MainThread) [custom_components.localtuya.pytuya] [525...12b] Waiting for sequence number 1
2022-01-04 08:36:58 DEBUG (MainThread) [custom_components.localtuya.pytuya] [525...12b] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2022-01-04 08:36:58 DEBUG (MainThread) [custom_components.localtuya.pytuya] [525...12b] Got heartbeat response
2022-01-04 08:36:58 DEBUG (MainThread) [custom_components.localtuya.pytuya] [525...12b] Decrypted payload: {}
2022-01-04 08:36:58 DEBUG (MainThread) [custom_components.localtuya.pytuya] [525...12b] Dispatching message TuyaMessage(seqno=1, cmd=10, retcode=0, payload=b'\x17\xf4\x10\xad\xa4\xf7\xc4<6\x1b\x81\x0f\xc1\xf4l\x00\xae \xa1\x9d\xf5\xc0wy\xd6\x8c&7i%KY\\\xcb\xa69M\xb7VJnW\xe6\xc8\xd8_x!?\xc9A\xa1\xad<1*\xf8\xc5\xe1\xb8\x8d\x8c20 e\x1d\x88S\xcbb\xdf\xb9\x7f\xc4n\x18\x90\x15\x9d\xac\xfaHBG\xcd\xeaD\x91\xa5Fj\xf0\x83Ex\x8aU\xd0\xfc4\xa9<\xba2\x11-W\x05\x18\xfd\xc1\x1b\xac\xcba7\xa9h\xda?\xc4\xd9\x8e\x1bnM\x8c\xf7\xf5S\xf5\xd4\xa2\xb6\xc83\xd8\xc5y\xf7\x05\xc7*', crc=4105660792)
2022-01-04 08:36:58 DEBUG (MainThread) [custom_components.localtuya.pytuya] [525...12b] Dispatching sequence number 1
2022-01-04 08:36:58 DEBUG (MainThread) [custom_components.localtuya.pytuya] [525...12b] Decrypted payload: {"devId":"5254718350029112012b","dps":{"1":true,"9":0,"18":435,"19":717,"20":2415,"21":1,"22":650,"23":30757,"24":18144,"25":1144}}
```

**Comment by codingcatgirl** [comment]
> And are you blocking DNS lookups as well as internet access, as per the 2nd note here? Just checking for completeness.
Yes, i'm blocking all access, i have read the docs :P

I'll try to get the startup logs in a big, but i think i already looked at them before and there was nothing in there. I'll check again soon though
