### ISSUE TITLE
Error message: The length of the provided data is not a multiple of the block length

### ISSUE THREAD

**Issue by ranrinc** [rospogrigio/localtuya#78]
I got this error messages which not sure why, also disable for the device on tuya integrations. Still got this messages during the startup, unsure what happen:

```
    raise ValueError("Config entry has already been setup!"),
ValueError: Config entry has already been setup!,
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry,
    return await hass.data[DOMAIN].async_setup_entry(entry),
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 67, in async_setup_entry,
    result = await component.async_setup_entry(hass, self)  # type: ignore,
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup,
Traceback (most recent call last):,
2020-10-13 14:38:59 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry AC Front Guest Room for sensor,
Failed to update status of device [xxx.xxx.xxx.xxx]: [The length of the provided data is not a multiple of the block length.]
```

**Comment by postlund** [comment]
Not sure about the config entry error, do you have any feeling of it is related? The other error is obviously some padding error. Is this reproducible for you? We need debug logs to go further.

**Comment by ranrinc** [comment]
> Not sure about the config entry error, do you have any feeling of it is related? The other error is obviously some padding error. Is this reproducible for you? We need debug logs to go further.

What do you need.. cause that error always come up upon reboot HA on my portainer error logs

**Comment by postlund** [comment]
I'm not sure how to debug the config entry error, not much to go on. But you can enable debug logs for localtuya for the other one:

```yaml
logger:
  default: warning
  logs:
    custom_components.localtuya:debug
```

**Comment by postlund** [comment]
I think I have reproduced the latter error myself, will try to fix it tonight. Will keep you posted.

**Comment by postlund** [comment]
@ranrinc I created a more "detailed" issued for the config flow error in #94. The other issue should probably be fixed by #92, which is now merged to `master`. Maybe you can try out `master` and see if the error disappears?

**Comment by ranrinc** [comment]
@postlund I just replace the current with new master, however I'm still seing this error

```
2020-10-19 17:09:01 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry AC Daikin Plug for sensor,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup,
    result = await component.async_setup_entry(hass, self)  # type: ignore,
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 67, in async_setup_entry,
    return await hass.data[DOMAIN].async_setup_entry(entry),
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry,
    raise ValueError("Config entry has already been setup!"),
ValueError: Config entry has already been setup!,
2020-10-19 17:09:01 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry AC Daikin Plug for sensor,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup,
    result = await component.async_setup_entry(hass, self)  # type: ignore,
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 67, in async_setup_entry,
    return await hass.data[DOMAIN].async_setup_entry(entry),
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry,
    raise ValueError("Config entry has already been setup!"),
ValueError: Config entry has already been setup!,
2020-10-19 17:09:02 WARNING (MainThread) [homeassistant.components.threshold.binary_sensor] State is not numerical,
```

**Comment by postlund** [comment]
Yeah, I will deal with the config entry stuff in the other issue. But great that the "block length" issue got resolved 👍

**Comment by postlund** [comment]
Does the config entry error appear at every startup of home assistant? My initial thought was that it appears if the config has changed between the already stored config entry and YAML.

**Comment by ranrinc** [comment]
I try reboot a couple of time.. still getting the same messages

**Comment by postlund** [comment]
@ranrinc Found the issue (explains in #94). Please try #100 and let me know if it works.

**Comment by ranrinc** [comment]
> @ranrinc Found the issue (explains in #94). Please try #100 and let me know if it works.

Well, currently my other plugs is broken so I only add single plugs. However, since all my other tuya devices are running tuya integration will this causing the error?

**Comment by postlund** [comment]
@ranrinc I don't know for sure if the regular integration causes any problems, but I wouldn't be surprised if it did. So I recommend disabling it when testing.

**Comment by ranrinc** [comment]
@postlund Finally today I remove tuya integration and change all into localtuya. So far its working however my power outlets which have 5 swich both come back with many error. Unsure what is the problem.

```
2020-10-25 17:57:54 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Family Room Outlet (YAML) for switch,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup,
    result = await component.async_setup_entry(hass, self)  # type: ignore,
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 73, in async_setup_entry,
    return await hass.data[DOMAIN].async_setup_entry(entry),
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry,
    raise ValueError("Config entry has already been setup!"),
ValueError: Config entry has already been setup!,
2020-10-25 17:57:54 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Family Room Outlet (YAML) for switch,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup,
    result = await component.async_setup_entry(hass, self)  # type: ignore,
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 73, in async_setup_entry,
    return await hass.data[DOMAIN].async_setup_entry(entry),
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry,
    raise ValueError("Config entry has already been setup!"),
ValueError: Config entry has already been setup!,
2020-10-25 17:57:54 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Family Room Outlet (YAML) for switch,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup,
    result = await component.async_setup_entry(hass, self)  # type: ignore,
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 73, in async_setup_entry,
    return await hass.data[DOMAIN].async_setup_entry(entry),
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry,
    raise ValueError("Config entry has already been setup!"),
ValueError: Config entry has already been setup!,
2020-10-25 17:57:54 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Family Room Outlet (YAML) for switch,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup,
    result = await component.async_setup_entry(hass, self)  # type: ignore,
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 73, in async_setup_entry,
    return await hass.data[DOMAIN].async_setup_entry(entry),
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry,
    raise ValueError("Config entry has already been setup!"),
ValueError: Config entry has already been setup!,
2020-10-25 17:57:54 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Mom Room Outlet (YAML) for switch,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup,
    result = await component.async_setup_entry(hass, self)  # type: ignore,
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 73, in async_setup_entry,
    return await hass.data[DOMAIN].async_setup_entry(entry),
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry,
    raise ValueError("Config entry has already been setup!"),
ValueError: Config entry has already been setup!,
2020-10-25 17:57:54 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Mom Room Outlet (YAML) for switch,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup,
    result = await component.async_setup_entry(hass, self)  # type: ignore,
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 73, in async_setup_entry,
    return await hass.data[DOMAIN].async_setup_entry(entry),
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry,
    raise ValueError("Config entry has already been setup!"),
ValueError: Config entry has already been setup!,
2020-10-25 17:57:54 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Mom Room Outlet (YAML) for switch,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup,
    result = await component.async_setup_entry(hass, self)  # type: ignore,
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 73, in async_setup_entry,
    return await hass.data[DOMAIN].async_setup_entry(entry),
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry,
    raise ValueError("Config entry has already been setup!"),
ValueError: Config entry has already been setup!,
2020-10-25 17:57:54 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Mom Room Outlet (YAML) for switch,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup,
    result = await component.async_setup_entry(hass, self)  # type: ignore,
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 73, in async_setup_entry,
    return await hass.data[DOMAIN].async_setup_entry(entry),
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry,
    raise ValueError("Config entry has already been setup!"),
ValueError: Config entry has already been setup!,
```

Furthermore need help in setting the light bulb, is there a detail yaml? Thanks in advance

**Comment by postlund** [comment]
@ranrinc Yeah, that's a bug in current version. It's fixed on `master`, so if you check out `master` instead you should not see those errors anymore.

**Comment by postlund** [comment]
Did you manage to test with `master`?

**Comment by ranrinc** [comment]
> Did you manage to test with `master`?

I have not yet to test on master.. I though should wait till it being update for release?

**Comment by ranrinc** [comment]
> Did you manage to test with `master`?

Finally have time to test it and yes all the error is now gone... Hope this will get release very soon. Need help with tuya light since currently only show single on/off only and unsure how to set it up.

**Comment by postlund** [comment]
@ranrinc Thanks for verifying! Will close the issue now.
